---
shortName: default
longName: Default configuration
description: |
    Default TPG configuration, without any customization
parameters:
    nbOfEvents: 50
    conditions: auto:phase2_realistic_T15
    beamspot: HLLHC14TeV
    geometry: Extended2026D49
    era: Phase2C9
    inputCommands: '"keep *","drop l1tTkPrimaryVertexs_L1TkPrimaryVertex__RECO"'
    procModifiers: empty
    filein: file:/data_CMS_upgrade/data_jenkins/Phase2HLTTDRSummer20ReRECOMiniAOD/TT_TuneCP5_14TeV-powheg-pythia8/FEVT/PU200_111X_mcRun4_realistic_T15_v1-v2/003ACFBC-23B2-EA45-9A12-BECFF07760FC.root
    customise: empty
    customise_commands: ''
