---
subsetName: default subset
description: Default set of comparisons
configuration:
    - ref: default
      test: default
    - ref: bcstc
      test: bcstc
    - ref: s1fw
      test: s1fw
    - ref: default
      test: s1fw
